### ISSUE TITLE
Error: "jsdom 4.x onward only works on io.js, not Node.js"

### ISSUE THREAD

**Issue by corvuscornix** [binarykitchen/gulp-jest-iojs#1]
I tried to use this module to overcome the FB iojs problem, but I was not able to get it working. When I try to run tests I get following error:
`jsdom 4.x onward only works on io.js, not Node.jsT: https://github.com/tmpvar
....

Is this because something has changed in the github:facebook/jest#0.5.x repository lately?

**Comment by binarykitchen** [comment]
@corvuscornix that's correct, this npm module is only for iojs and i haven't tested nor tried it on nodejs at all.

try to this to see if it works: `npm install && npm run test` on iojs and then you'll know the answer yourself. and do the same again for nodejs and it probably won't work.

**Comment by corvuscornix** [comment]
Thanks for the answer and sorry for my confusion. I think I finally got it working now. :)
